Fix negative values being sent to Datadog
bretcope/BosunReporter.NET pull request #51
Opened 2022-11-16 15:31 UTC by viveret

The negative sign for numbers is not taken into account when calculating the size of the encoding buffer, so writing negative values causes utf8writer to not be able to format it into the buffer.

This fixes the calculation by checking if the number is negative, and using the correct value when throwing an exception.

2022-11-16 15:36 UTC, deanward81 requested changes
@viveret looks good overall, but can you add tests? https://github.com/StackExchange/StackExchange.Metrics/blob/main/tests/StackExchange.Metrics.Tests/StatsdMetricHandlerTests.cs is the place to add to - I think you can get away with adding a few `InlineData` values at the top of `UdpUri_Counter_ReceivesValidStatsd`

2022-11-16 16:39 UTC, viveret commented
@deanward81 I added the test values

2022-11-16 21:20 UTC, deanward81 approved these changes

2022-11-16 21:21 UTC, merged

2023-02-16 11:44 UTC, svalbuena commented
@deanward81 when is this change going to be released in the nuget feed? Latest is 2.0.9, which I thought already contained this change, but it does not

2023-02-16 12:10 UTC, deanward81 commented
@svalbuena just published it from MyGet

2023-02-16 12:15 UTC, svalbuena commented
Thank you! @deanward81